[package]
name = "sensor"
version = "0.1.0"
edition = "2024"
default-run = "sensor"

[features]
default = ["mmap", "rayon"]
#default = ["mmap"]
#default = ["rayon"]
#default = []

humidity = []
mmap = ["dep:memmap2"]
rayon = ["dep:rayon"]  # Parallel iterators

[profile.release]
debug = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.3"
clap = { version = "4.5.36", features = ["derive"] }
clap_complete = "4.5.47"
iana-time-zone = "0.1.63"
#egui = "0.24.1"
#egui_tiles = "0.4.0"
memmap2 = { version = "0.9.5", optional = true }
rayon = { version = "1.10.0", optional = true }
winnow = "0.7.6"
zip = "2.6.1"

[profile.release-with-debug]
inherits = "release"
debug = true
